# Generated by Django 6.0.1 on 2026-04-08 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事件標題')),
                ('description', models.TextField(blank=True, verbose_name='事件描述')),
                ('passcode', models.CharField(max_length=20, unique=True, verbose_name='委員進入碼')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '競賽事件',
                'verbose_name_plural': '競賽事件',
            },
        ),
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='委員姓名')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioners', to='scoring_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='項目名稱')),
                ('weight', models.IntegerField(verbose_name='權重(%)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scoring_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='組別名稱')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='scoring_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='分數')),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scoring_app.commissioner')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_app.scoringitem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_app.team')),
            ],
            options={
                'unique_together': {('commissioner', 'team', 'item')},
            },
        ),
        migrations.CreateModel(
            name='TeamRankRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='序位')),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='scoring_app.commissioner')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_app.team')),
            ],
            options={
                'unique_together': {('commissioner', 'team')},
            },
        ),
    ]
